# Generated by Django 2.2.6 on 2019-11-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.Tag', verbose_name='标签'),
        ),
    ]
